In [1]:
import pandas as pd
import numpy as np
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [2]:
data_df = pd.read_csv("Data/data_with_industry_codes.csv")
questions_df = pd.read_csv("Data/questions.csv")
questions_df = questions_df.filter(['questions_id','questions_title','questions_date_added','questions_body'])
best_answer_df = pd.merge(data_df, questions_df, on="questions_id")
best_answer_df = best_answer_df.drop(columns=['Unnamed: 0'])
# best_answer_df_short = best_answer_df.head(10)
# best_answer_df_short

best_answer_df

questions_id                        answers_id  \
0      f6b9ca94aed04ba28256492708e74f60  7640a6e5d5224c8681cc58de860858f4   
1      00f9376f9c864631bc970f3a49c6aa08  26e01bf820d84de4952d5fe04aab62e1   
2      08a105aaa206418294d7bdf291e0235d  0f5615fcffb349d9b07e9a714d0573dc   
3      2c5bd5eb628245acb868c81fefcfe5e0  281c2557f0154dde984707e40100b8b4   
4      2f2378acab3f444199ee2b69d2d3626f  63b7a06323ee4d578a37cf780debfa58   
5      333464d7484b43e3866e86096bc4ddb9  683b200ad5014e84a441db677f990d75   
6      34feb9980e7742109adfab22828329f0  1ddd5ce4c80c4523bc055f7f4b66d4a1   
7      3738884893914f98bc9b6274248700fc  765f4a46b76c4c3496cbc2de6faf8c2d   
8      5bd585028efe49f4b89701b84e6fbe8c  d0388adf192c4683a1d9a079f88fbd52   
9      60824610a30541eda9e1e7ed6b7b3599  d27157b184a54761ab51f79fab878b0c   
10     700172696b9b48859d4a9855f1878ac5  9522aa09989043b88319bd1b2080b1bf   
11     71a6ab49a9444c60b45c458b57fa5960  90826bc9dd574074a5a56dffcb021d71   
12     749c5632a7c34f3f86590c9f8a1da2db  63118ff15bb142caba765d30cd2e71b0   
13     82acf6d8608b4743848d0c8c4e5c610b  ae8d6e375f804c698c324def1a3bf4f9   
14     8ce7dde9cbe04940bbcdf4577e7296f3  2b0a9b3c1f5c48168696ce1a614582c3   
15     9d211b99e17c46fbbaca03dc6b43f1c4  5d670d5f8700402ab56bae609b06d02d   
16     9dcea61327f545f7a0a3f75365477555  3ac551fd27224579944227533762164e   
17     a7bc96f56e0742a9a39bbb91d118b465  43aee8f10fb14ae2a235a95dbc05dfc4   
18     b3534776e3854e8bb73d8a1b1be3511f  f46ad30f5220449f9ac36f66f49ba310   
19     c9c6a69320874a0ca994a41073ca6a6b  37becf313a4a4526a0bb0c3d67d78b75   
20     ca209b4e19064d8e9834b3ca1a3f5361  7d1a41e5ef48410fa7ff647a4bf87eed   
21     d98717b213984ed1a715bd88367d6258  a836064f4eaf491eaeb4142e8d4cd752   
22     dfd33a7465f540989adf7795cbedb712  429ecea83a574e84affba375ce6da5ef   
23     e978b437413048c183e3cb556f90a878  6d823a750e294c75b10fafbbbaf19855   
24     fdce59131eb74b449fa20a1ceb898149  97eba893d7084b798575e13e39f774ae   
25     0025b917219c4a24ba5fe260ca66ca98  f9390f8f2e4a40f9876ba0d81604734a   
26     02d4ff95d2eb4bee881f6320a99dbc0b  ba39d1b1eb954cf2b26e3e13725ba6ec   
27     042bbf8655164b5ea67db345942fa4d4  ebb42a9209ef4c269a96986c8343cbbb   
28     0914db8647f14ed18ab2a7b321d0b81d  ca4491e34b144cf480fb854751d4c8ca   
29     09c872ce237842c1885d7f1584c6bdf5  a0ab7598b93e4f7bb13dab64d5708265   
...                                 ...                               ...   
22424  ff2e37a4ee3542e8968463b3499f648d  ff714f8ac3c044c785a5fe5a0a5c9249   
22425  081c9289dd5e49258e4224e1fe3e4b63  eee6a4fa0ce040ddaf60568aefa84d8a   
22426  8af30195ce3646729174a7d0a3ceaf71  153658272b224da1a0e7d514b360e1f2   
22427  23d3812ef6b24b279629b769105d09eb  d3d8c484e7a74532aeac1921f73f67dd   
22428  0c3bbf6f7b714e35868b7d26dc74af98  20bc5ecbb0294047a39bd93ffea4e22b   
22429  76d859078179418990bda99f28c3f054  a4936c692b8f47c3a35259e09662973e   
22430  e8c8ed32802b4090b5865dd3c2c3f42a  c75837f01ecd4f1cba57b0624a18733f   
22431  7b69abaa38e2491d935b66ed7953c326  e0ae91bc3ed343729d655e0daa6a920a   
22432  ea310e9eca8d4cd5991ecc6c047afd30  8fc97bbeb33d429cb166fbbdd2bcf13b   
22433  993e65ddbfd24ea2a133d8d96a7b6ceb  5d91c2d66e8448d088b4941869af2d8b   
22434  22d856b36b0144049c41c233da70337b  4c2e830bf8714e098181461b13b153dd   
22435  a7931d4e538f4a558c4f59e73e96b887  cc36ac9c07404717b7565a81143aa872   
22436  cdde8aaf6911492685982a4c728a9dff  37e86d94cf2e4c30adc4bc91d6a8f1ff   
22437  158bc55a058a4a5e9c4ee861c24e80d7  2ebfe053987c4a25a70acc4218d1f457   
22438  f4507b9a329743dc877b444364713bcd  afcc71704873454cb611260546bf53ff   
22439  f85e9591309b42fcb4fe7cc5b56fa346  a9f83ab87a3b4b26b9055122a0d5d5bc   
22440  03fd4382fd09420184827e522b0ae3b3  0c2600cbe13c4fbe8dbe3544fcff39af   
22441  2cca2904d3e24037b99b156009521955  30e6b58bf2664cc3befbf7f2f5d6324a   
22442  5aaac422880a434f85ad47b11557eddf  78ab159ab1c846c99435c05e2e21f691   
22443  b7310723d6bc4db3b3f30317dbd57598  b50f9a825ede4641972e8e8da2976fc1   
22444  d4b10756aac1424c

In [3]:
from cypher import encode
from datetime import datetime

In [4]:
best_answer_df['indexed'] = best_answer_df.apply(lambda x: encode(x['questions_title'], x['questions_body']), axis=1)

In [5]:
ba_df = best_answer_df
ba_df.dtypes

questions_id              object
answers_id                object
questions_id.1            object
professionals_industry    object
industry_codes             int64
questions_title           object
questions_date_added      object
questions_body            object
indexed                   object
dtype: object

In [6]:
ba_df['industry_codes'] = ba_df['industry_codes'].astype(int)
ba_df.dtypes

questions_id              object
answers_id                object
questions_id.1            object
professionals_industry    object
industry_codes             int64
questions_title           object
questions_date_added      object
questions_body            object
indexed                   object
dtype: object

In [7]:
indexed_padded = pad_sequences(best_answer_df['indexed'], value=0, padding='post', maxlen=50)

In [8]:
indexed_padded[666]

array([    1,  9913,     2, 13342, 14952, 14040, 17348, 16978, 17266,
       18305, 18045, 18103, 18429, 17447, 18219, 18422, 14040, 16660,
       17578, 18193, 17266, 10051, 17531,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0], dtype=int32)

In [9]:
import keras
import tensorflow as tf

In [10]:
from sklearn.model_selection import train_test_split

X=indexed_padded
y = best_answer_df["industry_codes"]

print(X.shape, y.shape)

(22454, 50) (22454,)


In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [ ]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_test_scaled[100]

/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([0.        , 0.99643185, 0.        , 0.99589167, 0.81701714,
       0.94875399, 0.99637818, 0.89437267, 0.88096654, 0.02373101,
       0.9945943 , 0.76523055, 0.78620466, 0.95480837, 0.98032326,
       0.97610682, 0.9503757 , 0.9775123 , 0.00432456, 0.88096654,
       0.88118277, 0.98740472, 0.90091356, 0.95372723, 0.98248554,
       0.95015947, 0.65430564, 0.88096654, 0.88096654, 0.95480837,
       0.78620466, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [ ]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
# label_encoder.fit(y_test)
encoded_y_train = label_encoder.transform(y_train)
# encoded_y_test = label_encoder.transform(y_test)
encoded_y_train

array([370, 386, 336, ..., 401, 386, 474])

In [ ]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
# y_test_categorical = to_categorical(encoded_y_test)

y_train_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# input shape is the vocabulary count used for the movie reviews (10,000 words)
# vocab_size = 10000
# model = keras.Sequential()
# model.add(keras.layers.Embedding(vocab_size, 50))
# model.add(keras.layers.GlobalAveragePooling1D())
# model.add(keras.layers.Dense(1, activation=tf.nn.relu))
# model.add(keras.layers.Dense(821, activation=tf.nn.relu))
# model.summary()

In [ ]:
# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=50))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=821, activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [ ]:
# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
X_train_scaled.dtype

dtype('float64')

In [ ]:
y_train_categorical.dtype

dtype('float32')

In [ ]:
# Fit the model to the training data
model.fit(
    X_train_scaled,
    encoded_y_train,
    epochs=1000,
    shuffle=True,
    verbose=1
)

Epoch 1/1000
15044/15044 [==============================] - 28s 2ms/sample - loss: 4.6898 - acc: 0.0981
Epoch 2/1000
15044/15044 [==============================] - 6s 420us/sample - loss: 4.4179 - acc: 0.1004
Epoch 3/1000
15044/15044 [==============================] - 6s 422us/sample - loss: 4.3801 - acc: 0.1004
Epoch 4/1000
15044/15044 [==============================] - 7s 454us/sample - loss: 4.3527 - acc: 0.1004
Epoch 5/1000
15044/15044 [==============================] - 7s 433us/sample - loss: 4.3307 - acc: 0.1004
Epoch 6/1000
15044/15044 [==============================] - 7s 433us/sample - loss: 4.3085 - acc: 0.1004
Epoch 7/1000
15044/15044 [==============================] - 8s 500us/sample - loss: 4.2905 - acc: 0.1004
Epoch 8/1000
15044/15044 [==============================] - 6s 417us/sample - loss: 4.2679 - acc: 0.1004
Epoch 9/1000
15044/15044 [==============================] - 6s 416us/sample - loss: 4.2446 - acc: 0.1004
Epoch 10/1000
15044/15044 [=============================

In [24]:
model_loss, model_accuracy = model.evaluate(
    X_train_scaled, encoded_y_train, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

 - 3s - loss: 1.8144 - acc: 0.4967
Normal Neural Network - Loss: 1.814405541634249, Accuracy: 0.49667641520500183


In [636]:
# Save the model
model.save("first_model_50.h5")